version: 2

jobs:
  build:
    docker:
      - image: "serega753/cpp_project:actual"
    working_directory: /app/TP_CPP_PROJECT
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: cd
          command: 'cd /app/TP_CPP_PROJECT'
      - run:
          name: cp cmake
          command: 'cp /app/net_cmake/CMakeLists.txt /app/TP_CPP_PROJECT/Net/'
      - run:
          name: Creating Build Files
          command: 'cmake Net/CMakeLists.txt && cd Net/ && make'
      - run:
          name: testing
          command: '/app/TP_CPP_PROJECT/Net/net_tests'