version: 2

jobs:
  build:
    docker:
      - image: "serega753/cpp_project:cpp1"
    working_directory: /app/TP_CPP_PROJECT
    steps:
      - checkout
      - run:
          name: cd
          command: 'cd /app/TP_CPP_PROJECT'
      - run:
          name: Linters
          command: './linters/run.sh --local'
      - run:
          name: Creating Build Files
          command: 'cmake server_side/test/CMakeLists.txt'
      - run:
          name: Unit Testing
          command: '/app/TP_CPP_PROJECT/server_side/test/tests'
      - run:
          name: valgrind
          command: 'valgrind /app/TP_CPP_PROJECT/server_side/test/tests'